# Generated by Django 4.2.9 on 2024-02-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessert',
            name='allergens',
            field=models.TextField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='dessert',
            name='description',
            field=models.TextField(default=1, max_length=250),
        ),
    ]
