# Generated by Django 4.2.9 on 2024-03-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_process'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='dessert',
            name='allergens',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='process',
            name='step',
            field=models.CharField(choices=[('R', 'Check Recipe'), ('I', 'Buy Ingredients'), ('B', 'Baking Day!')], default='R', max_length=1),
        ),
    ]
